# Generated by Django 5.0.6 on 2024-08-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='category_for_post',
        ),
    ]
