# Generated by Django 5.0.6 on 2024-08-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_category_postcategory_category_for_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_for_post',
            new_name='category',
        ),
    ]
